//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAplikacija.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfAplikacija.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani (esc.).
        /// </summary>
        public static string btnOdustani {
            get {
                return ResourceManager.GetString("btnOdustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi (enter).
        /// </summary>
        public static string btnPotvrdi {
            get {
                return ResourceManager.GetString("btnPotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži info:.
        /// </summary>
        public static string btnPrikazi {
            get {
                return ResourceManager.GetString("btnPrikazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi postavke i  pokreni aplikaciju (enter).
        /// </summary>
        public static string btnSpremi {
            get {
                return ResourceManager.GetString("btnSpremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekran.
        /// </summary>
        public static string cbiEkran {
            get {
                return ResourceManager.GetString("cbiEkran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string cbiEngleski {
            get {
                return ResourceManager.GetString("cbiEngleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string cbiHrvatski {
            get {
                return ResourceManager.GetString("cbiHrvatski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobitel.
        /// </summary>
        public static string cbiMobitel {
            get {
                return ResourceManager.GetString("cbiMobitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string cbiMuski {
            get {
                return ResourceManager.GetString("cbiMuski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puni Prikaz.
        /// </summary>
        public static string cbiPuniPrikaz {
            get {
                return ResourceManager.GetString("cbiPuniPrikaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet.
        /// </summary>
        public static string cbiTablet {
            get {
                return ResourceManager.GetString("cbiTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženski.
        /// </summary>
        public static string cbiZenski {
            get {
                return ResourceManager.GetString("cbiZenski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Golova:.
        /// </summary>
        public static string lblBrGolova {
            get {
                return ResourceManager.GetString("lblBrGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj na dresu:.
        /// </summary>
        public static string lblBrNaDresu {
            get {
                return ResourceManager.GetString("lblBrNaDresu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj primljenih golova:.
        /// </summary>
        public static string lblBrojPrimljenihGolova {
            get {
                return ResourceManager.GetString("lblBrojPrimljenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova:.
        /// </summary>
        public static string lblBrZabijenihGolova {
            get {
                return ResourceManager.GetString("lblBrZabijenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona:.
        /// </summary>
        public static string lblBrZutih {
            get {
                return ResourceManager.GetString("lblBrZutih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobivene utakmice:.
        /// </summary>
        public static string lblDobiveneUtakmice {
            get {
                return ResourceManager.GetString("lblDobiveneUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dohvačanje:.
        /// </summary>
        public static string lblDohvacanje {
            get {
                return ResourceManager.GetString("lblDohvacanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin:.
        /// </summary>
        public static string lblDomacin {
            get {
                return ResourceManager.GetString("lblDomacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa kod:.
        /// </summary>
        public static string lblFifaKod {
            get {
                return ResourceManager.GetString("lblFifaKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost:.
        /// </summary>
        public static string lblGost {
            get {
                return ResourceManager.GetString("lblGost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string lblIme {
            get {
                return ResourceManager.GetString("lblIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgubljene utakmice:.
        /// </summary>
        public static string lblIzgubljeneUtakmice {
            get {
                return ResourceManager.GetString("lblIzgubljeneUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        public static string lblJezik {
            get {
                return ResourceManager.GetString("lblJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string lblKapetan {
            get {
                return ResourceManager.GetString("lblKapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neriješene utakmice:.
        /// </summary>
        public static string lblNerijeseneUtakmice {
            get {
                return ResourceManager.GetString("lblNerijeseneUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrane utakmice:.
        /// </summary>
        public static string lblOdigraneUtakmice {
            get {
                return ResourceManager.GetString("lblOdigraneUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi promjene i izađi?.
        /// </summary>
        public static string lblPotvdi {
            get {
                return ResourceManager.GetString("lblPotvdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string lblPozicija {
            get {
                return ResourceManager.GetString("lblPozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika golova:.
        /// </summary>
        public static string lblRazlikGolova {
            get {
                return ResourceManager.GetString("lblRazlikGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija:.
        /// </summary>
        public static string lblReprezentacija {
            get {
                return ResourceManager.GetString("lblReprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija:.
        /// </summary>
        public static string lblRezolucija {
            get {
                return ResourceManager.GetString("lblRezolucija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zemlja:.
        /// </summary>
        public static string lblZemlja {
            get {
                return ResourceManager.GetString("lblZemlja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DAL;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Globalization;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using Utils.Konstante;
        ///
        ///namespace WindowsFormsAplikacija
        ///{
        ///    public partial class PocetnePostavke : Form
        ///    {
        ///        private static string SETTINGS_PATH = Path.Combine(Directory.GetParent(Directo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PocetnePostavke {
            get {
                return ResourceManager.GetString("PocetnePostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace WindowsFormsAplikacija
        ///{
        ///    partial class PocetnePostavke
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Required designer variable.
        ///        /// &lt;/summary&gt;
        ///        private System.ComponentModel.IContainer components = null;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Clean up any resources being used.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;disposing&quot;&gt;true if managed resources should be disposed; otherwise, false.&lt;/param&gt;
        ///        protected override void Dispose(bool disposing)
        ///        {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PocetnePostavke_Designer {
            get {
                return ResourceManager.GetString("PocetnePostavke_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PocetnePostavke_en {
            get {
                return ResourceManager.GetString("PocetnePostavke_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PocetnePostavke1 {
            get {
                return ResourceManager.GetString("PocetnePostavke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrač.
        /// </summary>
        public static string titleIgrac {
            get {
                return ResourceManager.GetString("titleIgrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glavni prozor.
        /// </summary>
        public static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string titlePostavke {
            get {
                return ResourceManager.GetString("titlePostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacije.
        /// </summary>
        public static string titleReprezentacija {
            get {
                return ResourceManager.GetString("titleReprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string titleZatvori {
            get {
                return ResourceManager.GetString("titleZatvori", resourceCulture);
            }
        }
    }
}
